version: '3'
services:
    app:
        build: .
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=redis
            - DB_PORT=6379
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - '6379:6379'
